name: Smartmirror.one CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint-test-build:
    name: Lint, Test and Build
    runs-on: ubuntu-latest
    outputs:
      packageVersion: ${{ steps.gitversion.outputs.semVer }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js Dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: npm

    - name: Setup GitVersion
      if: github.event_name != 'pull_request'
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine New Package Version
      if: github.event_name != 'pull_request'
      uses: gittools/actions/gitversion/execute@v0.9.7
      id: gitversion

    - name: Replace Package Version
      if: github.event_name != 'pull_request'
      run: sed -s -i "s/0.1.0-gitversion/${{ steps.gitversion.outputs.semVer }}/g" package.json

    - name: Install Project Dependencies
      run: npm ci

    - name: Lint Packages
      run: npm run lint

    - name: Test Packages
      run: npm test

    - name: Test Report - Backend
      uses: dorny/test-reporter@v1
      if: success() || failure() # run this step even if previous step failed
      with:
        name: Backend Jest Tests
        path: packages/backend/junit.xml
        reporter: jest-junit

    - name: Build Packages
      run: npm run build

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-result
        path: packages/**/dist

  package:
    name: Package Binaries
    runs-on: ${{ matrix.os }}
    needs: lint-test-build
    env:
      PACKAGE_VERSION: ${{ needs.lint-test-build.outputs.packageVersion }}
    if: github.event_name != 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js Dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: npm

    - name: Install Project Dependencies
      run: npm ci

    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-result
        path: packages

    - name: Generate Binary
      run: npm run update:dependencies && npm run package
      working-directory: packages/backend

    - name: Upload Binary for Release
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: packages/backend/_bins/*

  release:
    name: Release Version
    runs-on: ubuntu-latest
    needs: package
    env:
      PACKAGE_VERSION: ${{ needs.lint-test-build.outputs.packageVersion }}
    if: github.event_name != 'pull_request'
    
    steps:
    - name: Download Release Binaries
      uses: actions/download-artifact@v3
      with:
        name: release
        path: releases

    - name: Release Binaries to GitHub
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.PACKAGE_VERSION }}
        name: Smartmirror.one - Latest
        allow_override: true
        prerelease: true
        files: releases
